import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "DM Helper",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='flex flex-col w-full overflow-x-hidden bg-slate-500'>
					<div className='bg-primary sticky top-0 z-10'>
						<Navbar />
					</div>
					<div className='container self-center'>{children}</div>
				</div>
			</body>
		</html>
	);
}
